---
title: "Lab -1: Test YData Baseball package"
execute: 
  cache: false
format: 
  pdf:
    include-in-header: 
       text: |
         \newcommand{\textasciicaret}{\^{}}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
        text: |
         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{showspaces = false, showtabs = false, breaksymbolleft={}, breaklines}
---

# This is a test file

Testing

## Problem 1

In [4]:
# This cell contains code that hasn't yet been covered in the course.
# Make sure to run this cell and all cells below.

import pandas as pd
import numpy as np

## Problem 2

In [5]:
print("The ratio of a circle's perimeter to its diameter is %.50f..." % np.pi)

The ratio of a circle's perimeter to its diameter is 3.14159265358979311599796346854418516159057617187500...

## Problem 3

In [4]:
table = pd.DataFrame({'Easy as': [1, 2, 3]})
table

   Easy as
0        1
1        2
2        3

## Problem 4

In [5]:
df = pd.DataFrame(
    {
        "a": [1, 2, 3, 4],
        "b": [0.5, 4, 10, 13],
        "c": [True, True, False, True],
     }
)

df

   a     b      c
0  1   0.5   True
1  2   4.0   True
2  3  10.0  False
3  4  13.0   True

In [ ]:
# %%capture

!quarto render lab_-1.ipynb --to pdf

pandoc
  to: latex
  output-file: homework_00.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - \KOMAoption{captions}{tableheading}
  block-headings: true
  title: 'Homework 1: Intro to Python'


Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999997 (TeX Live 2025) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999997 (TeX Live 2025) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode


Output created: homework_00.pdf