---
execute: 
  cache: false
format: 
  pdf:
    include-in-header: 
       text: |
         \newcommand{\textasciicaret}{\^{}}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
        text: |
         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{showspaces = false, showtabs = false, breaksymbolleft={}, breaklines}
---

# Class 2

Plan for today:
- Look at retrosheet play-by-play data from the 2025 All-Star game.
- Review some of the basics of Python
- Briefly discuss numpy ndarrays/pandas Series
- Start discussing pandas DataFrames

In [16]:
import YData_baseball

YData_baseball.download_data("Lahman_2024u/Batting.csv")
YData_baseball.download_data("Lahman_2024u/People.csv")
YData_baseball.download_data("allstar_game_2025.csv")

The file `Batting.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `People.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `allstar_game_2025.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.

In [17]:
import pandas as pd
import numpy as np

## 1. Examining the 2025 All-Star game data

The cell below loads the retrosheet play-by-play data from the 2025 All-Star game. You will analyze this data more in lab 1.

In [18]:

allstar_game = pd.read_csv("allstar_game_2025.csv")

allstar_game.head(10)

,gid,event,inning,top_bot,vis_home,site,batteam,pitteam,score_v,score_h,...,pn,umphome,ump1b,ump2b,ump3b,umplf,umprf,date,gametype,pbp
0,NLS202507150,K,1,0,0,ATL03,ALS,NLS,0,0,...,1,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full
1,NLS202507150,K,1,0,0,ATL03,ALS,NLS,0,0,...,2,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full
2,NLS202507150,43/G4M,1,0,0,ATL03,ALS,NLS,0,0,...,3,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full
3,NLS202507150,S8/L8,1,1,1,ATL03,NLS,ALS,0,0,...,4,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full
4,NLS202507150,S4/G4S-.1-2,1,1,1,ATL03,NLS,ALS,0,0,...,5,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full
5,NLS202507150,D9/G3+.2-H;1-H,1,1,1,ATL03,NLS,ALS,0,0,...,6,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full
6,NLS202507150,53/G56,1,1,1,ATL03,NLS,ALS,0,2,...,7,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full
7,NLS202507150,K,1,1,1,ATL03,NLS,ALS,0,2,...,8,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full
8,NLS202507150,K,1,1,1,ATL03,NLS,ALS,0,2,...,9,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full
9,NLS202507150,7/L7LD+,2,0,0,ATL03,ALS,NLS,0,2,...,10,iassd901,hudsm901,segac901,viscj901,rehaj901,bacce901,20250715,allstar,full

## 2. Python basics

Let's very quickly review some of Python basics

### 2.1 Basics data types

Some of the main types of data in Python are:

- `int`: A whole number
- `float`: A decimal number
- `bool`: A logical value that can be True or False
- `strings`: A piece of text

We can also check what type of value is in a variable using the `type()` function.

In [19]:
# ints



# floats




# Booleans




# strings

### 2.2 Basic data structures

Some of the most widely used data structures in Python are lists, tuples, and dictionaries.

- Lists are created using [] brackets
- Tuples are created using () brackets
- Dictionaries are created using {} brackets

**Question 2.2** Please do the following: 

1. Create a list of the starting outfielders in the 2025 All-Star game for the American League (AL). The players are Aaron Judge, Javier Báez, and Riley Greene. Then, print out the first element in the list. Then replace the first element in the list with "Steven Kwan" and print out the updated list.

2. Repeat this process by creating a tuple of the same players and printing out the first element in the tuple. Then try to replace the first element in the tuple with "Steven Kwan" and see what happens. 

3. Finally, create a dictionary that maps the retrosheet player IDs to the player names for Shohei Ohtani, Aaron Judge, and Paul Skenes (these players' retrosheet player IDs are: ohtas001, skenp001 and judga001). Then print out the name of the player with the retrosheet ID "judga001".

In [20]:

# 1. Create a list of starting outfielders in all-star game 2025 for the AL



# 2. Get the first element of the list



# 1. Replace first element

In [21]:
# Tuples

In [22]:
# Dictionaries

### 2.3 Sequences and for loops

We can use for loops to iterate over sequences.

In [23]:
for i in range(5):
    print(i)

0
1
2
3
4

**Question 2.3** Please do the following: 

1. Write a for loop that prints out each player in the `OF_tuple`.
2. Then print out the fourth letter in the string "Aaron Judge".
3. Finally, write a for loop that prints out each letter in the string "Aaron Judge".

In [24]:
# 1. Loop over OF players

In [25]:
# strings are also sequences

outfielder = "Aaron Judge"


# Print out the fourth letter in the string



# Loop through each letter in his name

## 3. Array data

Numpy is a package that provides support for working with arrays. Numpy arrays (often called "ndarray") are similar to lists, but all elements in a numpy array must be of the same type (e.g., all integers, or all floats).

Pandas Series are similar to numpy arrays, but they have an index that allows you to label the elements in the Series. All operations that work on numpy arrays also work on pandas Series.

### 3.1 Array operations

We can easily add, subtract, and divide ndarrays of numbers that are the same length. We can also apply mathematical operations to arrays, such as `np.sum()`, `np.mean()`, `np.diff()`, etc.

**Question 3.1** Below are lists of Ohtani's seasons, earned runs, and innings pitched. Can you convert these lists to numpy arrays and calculate Ohtani's ERA (earned run average) for each season? The formula for ERA is: $$ERA = \frac{earned\_runs}{innings\_pitched} \times 9$$

In [26]:
import numpy as np

# Shohei Ohtani pitching stats by season

# Lists showing Ohtani's seasons, earned runs, and innings pitched
seasons = [2018, 2020, 2021, 2022, 2023, 2025]
earned_runs = [19, 7, 46, 43, 46, 15]
innings_pitched = [51.667, 1.667, 130.333, 166.0, 132.0, 47.0]


# Calculate ERA

### 3.2 Boolean arrays

We can create/use ndarrays of Booleans as well. 

Often we create these Boolean arrays by comparing elements of a numeric array to a particular value. 

We can use Boolean arrays to get elements from another array


**Question 3.1** Using Ohtani's pitching statistics, please do the following: 

1. Create a Boolean array called `over_50_innings` that has `True` values for seasons he pitched more than 50 innings.

2. Get the ERA for seasons with more than 50 innings pitched

3. Get the number of innings pitched in seasons he pitched over 50 innings

In [27]:

# 1. Get the boolean array that indicates which seasons Ohtani had more than 50 innings pitched

over_50_innings = ...


# 2. Get the ERA for seasons with more than 50 innings pitched

ERA_innings_over_50 = ...


# 3. Get the number of innings pitched in seasons he pitched over 50 innings

# 4. Pandas DataFrames

Pandas DataFrames are a data structure that allows you to store tabular data in Python. DataFrames are similar to spreadsheets, where each column can have a different type of data (e.g., integers, floats, strings). You can think of a DataFrame as a collection of pandas Series that share the same index. 

Let's explore pandas DataFrames by looking at the [Lahman Database](https://sabr.org/lahman-database/) which contains season level statistics on teams and baseball players (among other things).

### 4.1 Loading batting data

The file called `Batting.csv` contains batting statistics for all players from 1871 to 2024. We can load this data into Python as a pandas DataFrame into the name `batting` using the code below. The code also displays the first 5 rows of the DataFrame using the `.head()` method.

In [28]:
# Do not change this cell, just run it
import pandas as pd

# Load in the dataset from the class GitHub repository
batting = pd.read_csv('Batting.csv')  

batting.head(5)

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
0,aardsda01,2004,1,SFN,NL,11,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,aardsda01,2006,1,CHN,NL,45,NaN,2,0,0,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2,aardsda01,2007,1,CHA,AL,25,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,aardsda01,2008,1,BOS,AL,47,NaN,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
4,aardsda01,2009,1,SEA,AL,73,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

**Question 4.1.** What does each row in the data represent and what do the columns represent? Also, how many rows and columns are there in the batting table?  

Hint: using the `.shape` property can be useful here.


**Answers:**

- Each row represents: 
- Each column represents: 
-

### 4.2 Selecting a subset of columns from a DataFrame

We can select a subset of columns using the syntax: `my_df[["col1", "col2"]]`. 

**Question 4.2** Select the columns `playerID`, `yearID`, and `HR` from the batting table. Also, write down a reason why it might be useful to select a subset of columns in the answer section below.

**Answer:** The code below selects the requested columns. The reason that it is useful to select a subset of columns is because it can make it easier to see the information is relevant when only the relevant columns are available and it can also save computer memory.

### 4.3 Selecting a column as a pandas Series

We can also select a single column from a DataFrame as a pandas Series using the syntax: `my_df["col_name"]`. This is useful when we want to perform operations on a single column of data (e.g., operations that are similar to the operations we can perform on numpy arrays).

### 4.4 Using methods on columns in a DataFrame

The pandas Series and DataFrames also have methods that can operate on the values in a column. For example, we can sum the values in a column using the `my_df.sum()` method. We can also use numpy functions on columns of a DataFrame if we extract the data in the columns as pandas Series. For we can also sum the values in a column of a pandas DataFrame using `np.sum(my_df["col_name"]`. 

**Question 4.5**. What is the total number of home runs that have been hit from 1871 through the 2024 season? Please calculate this value using both the pandas `.sum()` method and the numpy `np.sum()` function. 

**Answer:** There have been 340,060 home runs hit from 1871 through 2024

In [29]:
import numpy as np

### 4.5 Selecting a subset of rows from a DataFrame

There are several ways to select rows from a pandas DataFrame. One way is by the rows absolute position in the DataFrame. To select rows by their position in the DataFrame, we can use the `iloc` method. For example, we can select rows 2, 5, and 6 using the syntax: `my_df.iloc[[2,5,6]]`.

We can also select rows based on Index values using `.loc`. For example, if we set the Index to the playerIDs using `batting2 = batting.set_index("playerID")`, we can then get a subset of rows based on the Index values. For example, we could get Hank Aaron's data using: `batting2.loc["aaronha01"]`.  


**Question 2.4:** Select the columns games, home runs, and stolen bases, and the rows 65470, 77657, 74271, and 88498 from the batting table. See if you can do this with **a single line of Python code**! Is there anything similar about these players' statistics?  

**Answer**: These players all have had seasons with 40 home runs and 40 stolen bases!

In [30]:

# Using this data, get rows 65470, 77657, 74271, and 88498

batting[['playerID', 'yearID','HR', 'SB']]

         playerID  yearID  HR    SB
0       aardsda01    2004   0   0.0
1       aardsda01    2006   0   0.0
2       aardsda01    2007   0   0.0
3       aardsda01    2008   0   0.0
4       aardsda01    2009   0   0.0
...           ...     ...  ..   ...
126902  zwilldu01    1915  13  24.0
126903  zwilldu01    1916   1   0.0
126904   zychto01    2015   0   0.0
126905   zychto01    2016   0   0.0
126906   zychto01    2017   0   0.0

[126907 rows x 4 columns]

In [31]:
# Also try out setting the Index to the playerID, and then getting Hank Aaron's data (playerID aaronha01)

### 4.6 Sorting rows of a DataFrame based on values in a column 

We can also sort values in a table using the `my_df.sort_values('col_name')` method. If we want to sort the columns from largest value to the smallest value we can set the additional argument `ascending = False` (i.e., `my_df.sort_values('col_name', ascending = False)`. 


**Question 4.6**. Use the sort function to find the player who has hit the most triples in a season. Can you figure out who this player is? 


**Answer**:  The player is [Chief Wilson](https://en.wikipedia.org/wiki/Chief_Wilson)

### 4.7 Boolean indexing and the .query() methods

As we discussed extensively in YData, you can use Boolean indexing and/or the `.query()` method to extract a DataFrame that only contains rows that meet particular conditions. For example, if we have a DataFrame called `my_df` that has a column called `vals` that has quantitative data, you could extract a DataFrame that only has rows where `vals` are greater than 10 using either:

- `my_df[my_df["vals"] > 10]`
- `my_df.query("vals > 10")`


**Question 4.7** Create DataFrame that only has information for batters/season where the hitters hit 60 or more home runs in a season.

In [32]:

# Using Boolean indexing





# Using the query method

### 4.8 Adding and renaming columns

We can add new columns to a DataFrame using the syntax `my_df["new_col_name"] = values`. The values can be a list, a numpy array, or a pandas Series which must be the same length as the DataFrame. 

We can also rename columns using the `.rename()` method. For example, we can rename the column "old_col_name" to "new_col_name" using the syntax `my_df.rename(columns = {"old_col_name": "new_col_name"})`.

**Question 4.8**. Create a new DataFrame called `batting2` that has all the same columns as the `batting` DataFrame but also has a new column in the batting DataFrame called "HR_per_game" that is the number of home runs hit divided by the number of games played. Then, rename the column "HR_per_game" to "HR/G".

In [33]:

# Make a copy of the DataFrame first, otherwise it will modify the original batting DataFrame...
batting2 = batting.copy()

### 4.9 Aggregate statistics by group

We can use the pandas `groupby()` and `.agg()` method to calculate aggregate statistics separately for different groups. For example, we can had a DataFrame called `my_df` that had a categorical column called "group_col" and a quantitative column called "quant_col", we could calculate the sum of the values in the "quant_col" separately for each unique value in the "group_col" using `my_df.groupby("group_col").agg(sum_vals = ("quant_col", "sum"))`

**Question 4.9** Please calculate how many games in total each major league baseball team played. Also, sort the values such that the team that has the most values is at the top of this aggregated DataFrame.

### 4.10 Joining/merging DataFrames

We can combine DataFrames together using the `.join()` and `.merge()` methods. The `join()` method joins to DataFrames based on the Index values, while the `.merge()` method joins two DataFrames based on values in columns in the two DataFrames. If we have two DataFrames called `df1` and `df2` that have the same Index values, we can join the using `df1.join(df2)`. Likewise, if the two DataFrame have columns with similar values (but difference Indexes) we can join them using `df1.merge(df2, left_on = "col_df1", right_on = "col_df2)`. We can also use the `how` argument to do, left, right, inner and full joins. 

**Question 4.10** The code below loads information about Major League Baseball player's into a DataFrame called `players`. Please join/merge this DataFrame with the `batting` DataFrame in such a way that all the rows in the `batting` DataFrame are preserved and the corresponding columns in the `players` DataFrame are joined on. Save the results of this joined DataFrame to the name `batting2` and print out the first 5 rows of `batting2`. 

Hint: The `playerID` column, which gives a unique for each baseball player, will be useful here!

In [34]:
# Loading the players DataFrame
players = pd.read_csv("People.csv")

players.head(3)

,ID,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,...,nameLast,nameGiven,weight,height,bats,throws,debut,bbrefID,finalGame,retroID
0,1,aardsda01,1981.0,12.0,27.0,Denver,USA,CO,NaN,NaN,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001
1,2,aaronha01,1934.0,2.0,5.0,Mobile,USA,AL,2021.0,1.0,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,aaronha01,1976-10-03,aaroh101
2,3,aaronto01,1939.0,8.0,5.0,Mobile,USA,AL,1984.0,8.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,aaronto01,1971-09-26,aarot101

In [35]:
# Join/merge the batting and the players DataFrames

In [36]:
%%capture

# You can run this code to covert this Jupyter notebook into a pdf
!quarto render class_02.ipynb --cache-refresh --to pdf