---
execute: 
  cache: false
format: 
  pdf:
    include-in-header: 
       text: |
         \newcommand{\textasciicaret}{\^{}}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
        text: |
         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{showspaces = false, showtabs = false, breaksymbolleft={}, breaklines}
---

# Baseball Lab 1: Python basics, numpy, and pandas

In today's lab exercises you'll practice:

1. Examine the retrosheet play-by-play data using basic Python data structures
2. Explore the Lahman batting data using numpy arrays/pandas Series
3. Use pandas to analyze the Lahman batting data

Please complete this notebook by filling in the cells provided. For all problems that you must write explanations and sentences for, please provide your answer in the designated space. 


#### Deadline

This assignment is due **Wednesday January 28th at 11pm** (this will likely be the only assignment that is not turned in on a Sunday). You can turn in the assignment up to 24 hours late for 90% credit (after that, the homework will only be accepted with a Dean's Extension). Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged. Refer to the policies page to learn more about how to learn cooperatively. You should start early so that you have time to get help if you're stuck. If you have questions, please post them to [Ed Discussion](https://edstem.org/us/courses/89102/discussion) (and answer other's questions too).

## Getting started - downloading the data

In order to complete this lab, it is necessary to download a few files. Please run the code below **only once** to download data needed to complete the lab. To run the code, click in the cell below and press the play button (or press shift-enter).

In [1]:
# Please run this code once to download the files you will need to complete the homework 

import YData_baseball

YData_baseball.download_data("Lahman_2024u/Batting.csv")
YData_baseball.download_data("allstar_game_2025.csv")
YData_baseball.download_data("george_springer.csv")

The file `Batting.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `allstar_game_2025.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `george_springer.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.

# Part 0: Quote and reaction to Astroball chapter 1 (5 points)

Please find an interesting quote from chapter 1 of Astroball (preface or prologue) and then write a ~one paragraph reaction to the quote below.

*Quote:*  ...

Reaction: ...

# Part 1. Using Retrosheet data to examine the 2025 All-Star Game

In class we will watch an inning of the 2025 [All-Star Game](https://www.mlb.com/video/2025-all-star-game-x2225). Let's look at the retrosheet play-by-play data from this game. 


## 1.1 The retrosheet play-by data

The code below loads the retrosheet play-by-play data (we will just refer to this as the 'retrosheet data') into a pandas DataFrame. The code then creates a DataFrame called `allstar_game` that has a subset of columns that are of interest, and displays the first 5 rows of the DataFrame. Details on how to interpret these event files can be found on the [retrosheet website](https://www.retrosheet.org/eventfile.htm#5). 

**Question 1.1 (4 points)**: To start, please answer the following questions about the data.

1. What does each row of the `allstar_game` DataFrame correspond to?
2. What information does the column `outs_pre` contain?


**Answers:** 

1.

2.

In [2]:
import pandas as pd
import numpy as np

# Load in the dataset
allstar_game_full = pd.read_csv("allstar_game_2025.csv")

allstar_game = allstar_game_full[["gid", "inning", "top_bot", "outs_pre", "score_v", "score_h", "batteam", "batter", 'pitcher', "pitches", "event"]] 

allstar_game.head()

,gid,inning,top_bot,outs_pre,score_v,score_h,batteam,batter,pitcher,pitches,event
0,NLS202507150,1,0,0,0,0,ALS,torrg001,skenp001,FBTBS,K
1,NLS202507150,1,0,1,0,0,ALS,greer003,skenp001,BCCBFBS,K
2,NLS202507150,1,0,2,0,0,ALS,judga001,skenp001,CX,43/G4M
3,NLS202507150,1,1,0,0,0,NLS,ohtas001,skubt001,FFBX,S8/L8
4,NLS202507150,1,1,0,0,0,NLS,acunr001,skubt001,FSBX,S4/G4S-.1-2

## 1.2 Decoding the meaning of the pitches column

The second plate appearance in the 2025 All-Star Game was by Riley Greene (batter `greer003`). As we can see from the `event` column (and as we saw in class), Riley Greene struck out (`K` in the `event` column). 

**Question 1.2 (5 points)**  Use data in the `pitches` column, and the [retrosheet code book](https://www.retrosheet.org/eventfile.htm#5) in the section titled 'The pitches field of the play record', to list the sequences of pitches that happened during this plate appearance. 


**Answer** 

The sequences of pitches that led to Riley Greene striking out was:

* The first pitch was a B = ball
* The second pitch was a ...
* The third pitch was a ...
* The fourth pitch was a ...
* The fifth pitch was a ...
* The sixth pitch was a ...
* The seventh pitch was a ...

## 1.3 Creating a dictionary mapping pitches to pitch names

Let's now create a dictionary called `pitches_dict` that maps the pitch codes to the pitch names (e.g., maps "B" into "ball)"

**Question 1.3 (5 points)** The code below starts creating the `pitches_dict` dictionary. Please add to it all the other pitch codes and their meanings for the pitches that were thrown to Riley Greene (you can ignore other pitch events that did not occur in this plate appearance).

In [3]:
pitches_dict = {"B": "ball",        }

## 1.4 Printing out each pitch 

Now that we have the `pitches_dict` dictionary, we can print out the pitches that occurred in Riley Greene's plate appearance using a for loop. 

**Question 1.4 (5 points)** The pitches that occurred in Riley Greene's plate appearance are stored in the variable `pitch_seq`. Please use a for loop (and the `pitches_dict` you created above) to print out the names of pitches that occurred in Riley Greene's plate appearance.

In [4]:
pitch_seq = "BCCBFBS"

# Part 2. Array and Series operations

Two fundamental packages in the Python data science ecosystem are [numpy](https://numpy.org/) and [pandas](https://pandas.pydata.org/). Numpy is a package that provides support for working with arrays, while pandas is a package that provides support for working with tabular data (i.e., data in tables). In this part of the lab, we will practice some basic calculations using numpy and pandas. 

Numpy arrays are similar to lists, but all elements in a numpy array must be of the same type (e.g., all integers, or all floats). Numpy arrays are more efficient than lists for numerical calculations because they are implemented in C and use contiguous memory locations. This means that numpy arrays can be processed more quickly than lists, especially when working with large datasets. 

Pandas Series are similar to numpy arrays, but they have an index that allows you to label the elements in the Series. This makes it easier to work with data that has a specific meaning, such as time series data or data with categorical labels. Pandas Series also have many built-in methods for performing calculations and transformations on the data. 

In the following exercise we will practice using numpy arrays and pandas Series to perform calculations on baseball data. In particular, we will look at [George Springer's](https://en.wikipedia.org/wiki/George_Springer) season level batting statistics (from the Lahman Database) and calculate some derived statistics such as batting average and slugging percentage. 

The code below loads George Springer's batting data into a pandas DataFrame called `george_springer`. The code then displays the first 5 rows of the DataFrame.

In [5]:
george_springer = pd.read_csv("george_springer.csv")

george_springer.head()

,playerID,retroID,yearID,teamID,G,AB,R,H,2B,3B,HR,RBI,SB,BB,SO
0,springe01,sprig001,2014,HOU,78,295,45,68,8,1,20,51.0,5.0,39,114.0
1,springe01,sprig001,2015,HOU,102,388,59,107,19,2,16,41.0,16.0,50,109.0
2,springe01,sprig001,2016,HOU,162,644,116,168,29,5,29,82.0,9.0,88,178.0
3,springe01,sprig001,2017,HOU,140,548,112,155,29,0,34,85.0,5.0,64,111.0
4,springe01,sprig001,2018,HOU,140,544,102,144,26,0,22,71.0,6.0,64,122.0

# 2.1 Create singles Series

You will notice that the `george_springer` DataFrame has a column called `H` that contains the number of hits George Springer had in each season (where hits are the sum of singles, doubles, triples, and home runs). However, this DataFrame does not contain the number of singles he had in each season. To calculate the number of singles, we can subtract the number of doubles, triples, and home runs from the total number of hits. 

We can extract Series from a DataFrame by using the syntax `my_df["col_name"]`, where `my_df` is the DataFrame and `col_name` is the name of the column we want to extract. Also, if we have two Series, we can perform element-wise operations on them using the `+`, `-`, `*`, and `/` operators. For example, if we have two Series called `s1` and `s2`, we can add them together using `s1 + s2`. 

**Question 2.1 (5 points)**: Please calculate the number of singles George Springer had in each season and store it in a new Series called `george_springer_1B`. Be sure to print out the Series to show your work (your Series should have as many elements as there are seasons in the `george_springer` DataFrame).

## 2.2 Get season level slugging percentage

We can also use pandas Series to calculate derived statistics such as batting average (AVG) and slugging percentage (SLG). Batting average is calculated as the number of hits divided by the number of at-bats, while slugging percentage is calculated using the formula: $$SLG = \frac{1B + 2 \times 2B  + 3 \times 3B  + 4 \times HR }{AB}$$ where $1B$ is the number of singles, $2B$ is the number of doubles, $3B$ is the number of triples, and $HR$ is the number of home runs. 

**Question 2.2 (5 points)**: Please calculate the slugging percentage for George Springer in each season and store them in new Series called `george_springer_SLG`. Be sure to print out the Series to show your work (your Series should have as many elements as there are seasons in the `george_springer` DataFrame).

In [6]:
# 2.2 Get season level SLG

## 2.3 Career Slugging Percentage

Finally, let's calculate George Springer's career slugging percentage. To do this, we will sum the number of singles, doubles, triples, and home runs and at-bats across all seasons and then calculate the slugging percentage of these totals

**Question 2.3 (5 points)**: Please calculate George Springer's career slugging percentage (through the 2024 season) and print it out. You can use results you calculated in previous exercises (e.g., `george_springer_1B` Series) if you find that helpful.

Note: Career slugging percentage is not just the average of the slugging percentage for each year.

In [7]:
import numpy as np

# Part 3. Using pandas to analyze season-level data from the Lahman database

Let's use pandas DataFrame to do a few simple analyses on the Lahman season-level batting data. The Lahman batting data is loaded below and the first 5 rows are shown. Please use this data for the rest of these exercises.

In [8]:
batting = pd.read_csv("Batting.csv")  

batting.head()

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
0,aardsda01,2004,1,SFN,NL,11,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,aardsda01,2006,1,CHN,NL,45,NaN,2,0,0,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2,aardsda01,2007,1,CHA,AL,25,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,aardsda01,2008,1,BOS,AL,47,NaN,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
4,aardsda01,2009,1,SEA,AL,73,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

## 3.1 Getting a subset of columns from the Lahman data

Often when working with pandas DataFrames, we will only be interested in a subset of the columns in the DataFrame. Removing superfluous columns can make it easier to work with the data, and can also speed up calculations. 

**Question 3.1 (5 points)**: Please create a new DataFrame called `batting2` that contains only the following columns from the `batting` DataFrame: `playerID`, `yearID`, `teamID`, `G`, `AB`, `R`, `H`, `2B`, `3B`, `HR`, `RBI`, `SB`, `BB`, and `SO`. Then print out the first 5 rows of this new DataFrame to show your work.

In [9]:
# get only a subset of columns, call this `batting2`

# 3.2 Red Sox data

Let's now get data from only the best baseball team; i.e., the Boston Red Sox!  

**Question 3.2 (5 points)**: Please create a new DataFrame called `redsox_data` that contains only the rows from the `batting2` DataFrame where the `teamID` is "BOS". Then print out the first 5 rows of this new DataFrame to show your work.

# 3.3 Red Sox season home run leader

Which baseball player had the most home runs in a season for the Red Sox? 

**Question 3.3 (5 points)**: Please find the player who had the most home runs in a season for the Red Sox. To do this start with the `redsox_data` DataFrame and create a DataFrame that has only a single row which has only the player who had the most home runs in a season for the Red Sox (i.e., your results should be a single row of the `redsox_data` DataFrame). As always, be sure to print out this DataFrame to show your work.

## 4. Explore the Lahman batting data on your own (8 points)

Please explore the Lahman batting data on your own and report something interesting that you found in the data!

**Note**: There is a fair amount freedom to the degree that you challenge yourself here, and we will be relatively relaxed on the grading of this question. If you find the questions in this lab were easy, then challenge yourself to do a more complex analysis. Conversely, if you found the above lab challenging, then just come up with a simple analysis (e.g., a couple lines of code), and make sure you understand all the code we have covered in class so far.

# 5.  Submitting your work

Once you're finished filling in and running all cells, you should submit your assignment as a pdf on Gradescope. You can access Gradescope through Canvas on the left-side of the class home page. The problems in each lab assignment are numbered. When submitting on Gradescope, please **make sure to select the correct pages of your pdf that correspond to each problem**. Failure to mark pages correctly **will result in points being deducted** from your score.

To convert this Jupyter notebook document to a pdf please run the code in the cell below. This should produce a document called `lab_01.pdf` which should appear in the files tab on the left (you might need to refresh the files tab to see this file). You can then right click on this file (command click on a mac), to download this pdf document which you can upload to Gradescope. 

Please be sure to check that all the code and output are visible before submitting your pdf to Gradescope as **points will be deducted for missing code and output that is not visible** since we will not be able to grade this.

In [10]:
%%capture

!quarto render lab_01.ipynb --cache-refresh --to pdf

#### Alternative submission instructions

If converting your Jupyter notebook to a pdf using the command in the cell above does not work, an alternative way to convert your Jupyter notebook is:

1.  Go to "File" at the top-left of your Jupyter Notebook
2.  Under "Download as" (or "Save and Export Notebook As...") and select "HTML (.html)"
3.  After the .html has downloaded, open it and then select "File" and "Print" (note you will not actually be printing)
4.  From the print window, select the option to save as a .pdf