---
execute: 
  cache: false
format: 
  pdf:
    include-in-header: 
       text: |
         \newcommand{\textasciicaret}{\^{}}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
        text: |
         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{showspaces = false, showtabs = false, breaksymbolleft={}, breaklines}
---

# Baseball Lab 0: Getting started analyzing baseball data using Python!

Welcome to YData: Baseball data analysis!  Most class meeting times will include a lecture portion as well as time spent analyzing data in Python. Based on the historical development of this class, the problem sets/homework for this class will be referred to as "labs". In some classes (such as today's class) we will begin on these labs during class time. Usually, these labs will be turned in on Gradescope for credit (due on Sunday evenings). However, this lab will **not** be turned in. 

In today's lab exercises you'll practice:

1. Writing and evaluating some basic *expressions* in Python
2. Using pandas to manipulate baseball data through some guided exercises
3. Using pandas to try to recreate statistics shown on baseball cards

In [1]:
## If you are using Google Colabs, you should install the YData_baseball package 
# and mount the your google drive by uncommenting and running the code below

# !pip install https://github.com/emeyers/YData_baseball_package.git
# from google.colab import drive
# drive.mount('/content/drive')

## 0. Downloading the data for today's class

Please run the code in the cell below to download the data for today's class.

In [2]:
import YData_baseball

YData_baseball.download_data("Lahman_2024u/Batting.csv")
YData_baseball.download_data("Lahman_2024u/People.csv")

## 1. Warm-up: Examining Houston Astros outfielders in 2017

Let's start practicing some basic calculations in Python by examining the Houston Astros outfielders in 2017! 

In 2017, the Houston Astros had three players with more than 100 games in the outfield. The roster of the Houston Astros outfielders can be found at https://www.baseball-reference.com/teams/HOU/2017-roster.shtml

### 1.1 Assignment

Recall that Python uses assignment statements to assign a value to a variable name.
An assignment statement has a name on the left side of an = sign and an expression to be evaluated on the right. For example, we can assign the value of 16 to `Marisnick_HR` using the following:

In [3]:
Marisnick_HR = 16
Marisnick_HR

16

Notice we also listed `Marisnick_HR` below the assignment so Python would print it's value.  If we did not include that second line, then the value would not have printed. Only the last variable that is listed by itself will be printed. If we would like to print the values for several variables we can use the `print()` function. 

Now that we have assigned a value to `Marisnick_HR` variable, Python will use this value whenever we use the name `Marisnick_HR`.

**Question 1.1**. Assign the names `Reddick_HR` and `Springer_HR` to the number of home runs hit by these Houston outfielders and print these values. Also, assign the number of at plate appearances (PA) these players had to the names `Marisnick_PA`, `Reddick_PA` and `Springer_PA.`

In [4]:
# Replace the ... with your answer

# Astros home runs (HR)
Reddick_HR = ...
Springer_HR = ...

# print the number of home runs by Reddick and Springer



# Astros plate appearances (PA)
Marisnick_PA = ...
Reddick_PA = ...
Springer_PA = ...

### 1.2 Calculating values

Now that we have the number of home runs and plate appearances as named variables, we can use the variable names to compute quantities like the total number of home runs each the outfields of each time hit, and the home run rate (HR/PA) the team hit.

**Question 1.2.** Calculate the home run rates (HR/PA) for the 2017 Astros outfielders and print this rate.

**Answer:**

### 1.3 Slightly more complex calculations

[Bill James](https://en.wikipedia.org/wiki/Bill_James) created a formula to predict the winning percentage a team would have based on the number of runs the team scored (R) and the number or runs the team allowed (RA). This formula, called the [Pythagorean expectation](https://en.wikipedia.org/wiki/Pythagorean_expectation), has the form:

Winning percentage = $\frac{R^2}{R^2 + RA^2}$


**Question 1.3.** In 2017, Houston had a record of 101-61. They also scored 869 runs and gave up 700 runs. Please complete the following steps:

1. Assign the number of runs they scored to a variable called `R`
2. Assign the number of runs allowed to a variable called `RA`
3. Assign their winning percentage to a variable called `WPCT`
4. Use the Pythagorean formula to calculate the winning percentage and assign it to a variable called `pred_WPCT`
5. Calculate the absolute value of the difference between the team's actual winning percentage and the predicted winning percentage.
6. Report the absolute difference in the number of wins that is predicted by the Pythagorean_expectation formula compared to how many wins the team actually had (hint: there are 162 games in a season).

Does the Pythagorean expectation formula seem accurate in this case? 


**Answers:** Use the code section below to calculate your results and then answer the questions here.

## 2. Using pandas to analyze data from the Lahman database

As you saw above, entering data by hand is not that much fun, and it would be prohibitively difficult to do many interesting baseball analyses if you had to enter all the data by hand. Fortunately the baseball community has worked together to compile baseball statistics related to many different aspects of the game in several different data set. One such data set is the [Lahman Database](https://sabr.org/lahman-database/) which contains season level statistics on teams and baseball players (among other things). 

In the following exercises you will use pandas to extract information from data that is part of the Lahman database. For these exercises, I am assuming you are familiar with the main pandas methods that were covered in YData. Depending on the background of students in the class, I can spend more time reviewing these pandas methods next class.

### 2.1 Loading batting data

The file called `Batting.csv` contains batting statistics for all players from 1871 to 2024. We can load this data into Python as a pandas DataFrame into the name `batting` using the code below. The code also displays the first 5 rows of the DataFrame using the `.head()` method.

In [5]:
# Do not change this cell, just run it
import pandas as pd

# Load in the dataset from the class GitHub repository
batting = pd.read_csv('Batting.csv')  

batting.head(5)

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
0,aardsda01,2004,1,SFN,NL,11,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,aardsda01,2006,1,CHN,NL,45,NaN,2,0,0,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2,aardsda01,2007,1,CHA,AL,25,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,aardsda01,2008,1,BOS,AL,47,NaN,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
4,aardsda01,2009,1,SEA,AL,73,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

**Question 2.1.** What does each row in the data represent and what do the columns represent? Also, how many rows and columns are there in the batting table?  

**Answers:**

- Each row represents ...
- Each column represents ...
- There are XXX rows in the table and YYY columns in the table

### 2.2 Selecting a subset of columns from a DataFrame

We can select a subset of columns using the syntax: `my_df[["col1", "col2"]]`. 

**Question 2.2** Select the columns `playerID`, `yearID`, and `HR` from the batting table. Also, write down a reason why it might be useful to select a subset of columns in the answer section below.

**Answer:**

### 2.3 Selecting a subset of rows from a table based on position

There are several ways to select rows from a pandas DataFrame. One way is by the rows absolute position in the DataFrame. To select rows by their position in the DataFrame, we can use the `iloc` method. For example, we can select rows 2, 5, and 6 using the syntax: `my_df.iloc[2,5,6]`


**Question 2.3:** Select the columns games, home runs, and stolen bases, and the rows 65470, 77657, 74271, and 88498 from the batting table. See if you can do this with **a single line of Python code**! Is there anything similar about these players' statistics?  

**Answer**:

### 2.4 Using methods on columns in a DataFrame

The pandas Series and DataFrames also have methods that can operate on the values in a column. For example, we can sum the values in a column using the `my_df.sum()` method. We can also use numpy functions on columns of a DataFrame if we extract the data in the columns as pandas Series. For we can also sum the values in a column of a pandas DataFrame using `np.sum(my_df["col_name"]`. 

**Question 2.4**. What is the total number of home runs that have been hit from 1871 through the 2024 season? Please calculate this value using both the pandas `.sum()` method and the numpy `np.sum()` function. 

**Answer:**

In [6]:
import numpy as np

# Using the pandas .sum() method



# Using numpy np.sum()

### 2.5 Sorting values in a column of data in a table

We can also sort values in a table using the `my_df.sort_values('col_name')` method. If we want to sort the columns from largest value to the smallest value we can set the additional argument `ascending = False` (i.e., `my_df.sort_values('col_name', ascending = False)`. 


**Question 2.5**. Use the sort function to find the player who has hit the most triples in a season. Can you figure out who this player is? 


**Answer**:

### 2.6 Boolean indexing and the .query() methods

As we discussed extensively in YData, you can use Boolean indexing and/or the `.query()` method to extract a DataFrame that only contains rows that meet particular conditions. For example, if we have a DataFrame called `my_df` that has a column called `vals` that has quantitative data, you could extract a DataFrame that only has rows where `vals` are greater than 10 using either:

- `my_df[my_df["vals"] > 10]`
- `my_df.query("vals > 10")`


**Question 2.6** Create DataFrame that only has information for batters/season where the hitters hit 60 or more home runs in a season.

### 2.7 Joining/merging DataFrames

We can combine DataFrames together using the `.join()` and `.merge()` methods. The `join()` method joins to DataFrames based on the Index values, while the `.merge()` method joins two DataFrames based on values in columns in the two DataFrames. If we have two DataFrames called `df1` and `df2` that have the same Index values, we can join the using `df1.join(df2)`. Likewise, if the two DataFrame have columns with similar values (but difference Indexes) we can join them using `df1.merge(df2, left_on = "col_df1", right_on = "col_df2)`. We can also use the `how` argument to do, left, right, inner and full joins. 

**Question 2.7** The code below loads information about Major League Baseball player's into a DataFrame called `players`. Please join/merge this DataFrame with the `batting` DataFrame in such a way that all the rows in the `batting` DataFrame are preserved and the corresponding columns in the `players` DataFrame are joined on. Save the results of this joined DataFrame to the name `batting2` and print out the first 5 rows of `batting2`. 

Hint: The `playerID` column, which gives a unique for each baseball player, will be useful here!

In [7]:
# Loading the players DataFrame
players = pd.read_csv("People.csv")

players.head(3)

,ID,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,...,nameLast,nameGiven,weight,height,bats,throws,debut,bbrefID,finalGame,retroID
0,1,aardsda01,1981.0,12.0,27.0,Denver,USA,CO,NaN,NaN,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001
1,2,aaronha01,1934.0,2.0,5.0,Mobile,USA,AL,2021.0,1.0,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,aaronha01,1976-10-03,aaroh101
2,3,aaronto01,1939.0,8.0,5.0,Mobile,USA,AL,1984.0,8.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,aaronto01,1971-09-26,aarot101

In [8]:
# Join/merge the batting and the players DataFrames

### 2.8 Aggregate statistics by group

We can use the pandas `groupby()` and `.agg()` method to calculate aggregate statistics separately for different groups. For example, we can had a DataFrame called `my_df` that had a categorical column called "group_col" and a quantitative column called "quant_col", we could calculate the sum of the values in the "quant_col" separately for each unique value in the "group_col" using `my_df.groupby("group_col").agg(sum_vals = ("quant_col", "sum"))`

**Question 2.8** Please calculate how many games in total each major league baseball team played. Also, sort the values such that the team that has the most values is at the top of this aggregated DataFrame.

## 3. Challenge question: Recreating your baseball card data

In class, everyone should have been given a baseball card. Please use the Lahman data to see if you can construct the statistics that are shown on the baseball card as accurately as possible; i.e., create a DataFrame that has all the statistics that are on your baseball card (and only the statistics) that are on your baseball card, including the total/aggregate statistics. 

Hint: It could be useful to write functions that will create derived statistics such as batting average (AVG) and slugging percentage (SLG) from the Lahman batting data. To do this, you might have to create other intermediate statistics as well (such as the number of single as a player hit). 

Note This is a challenging question, so do not worry if you are not able to complete it as we will likely work on this problem more next class.

## 4. Exploring the Lahman batting data on your own

If there is time, continue exploring the Lahman batting data on your own and report three findings you think are interesting. Also describe any additional capabilities you wish you knew how to do that would enable you to answer additional interesting questions.

**Conclusion:**  Congratulations, you have finished the first lab.  Remember that this lab is not graded, though the remaining labs this semester will be submitted for a grade.

In [9]:
%%capture

!quarto render lab_00.ipynb --cache-refresh --to pdf