---
execute: 
  cache: false
format: 
  pdf:
    include-in-header: 
       text: |
         \newcommand{\textasciicaret}{\^{}}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
        text: |
         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{showspaces = false, showtabs = false, breaksymbolleft={}, breaklines}
---

# Baseball Lab 2: Creating baseball cards

In today's lab exercises you'll practice doing more advanced pandas operations, writing functions, and using the Lahman database to analyze baseball data. 

Please complete this notebook by filling in the cells provided. For all problems that you must write explanations and sentences for, please provide your answer in the designated space. 


#### Deadline

This assignment is due **Sunday February 1st at 11pm**. You can turn in the assignment up to 24 hours late for 90% credit (after that, the homework will only be accepted with a Dean's Extension). Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged. Refer to the policies page to learn more about how to learn cooperatively. You should start early so that you have time to get help if you're stuck. If you have questions, plase post them to [Ed Discussion](https://edstem.org/us/courses/89102/discussion) (and answer others' questions too).

## Getting started - downloading the data

In order to complete this lab, it is necessary to download a few files. Please run the code below **only once** to download data needed to complete the lab. To run the code, click in the cell below and press the play button (or press shift-enter).

In [1]:
# Please run this code once to download the files you will need to complete the homework 

import YData_baseball

YData_baseball.download_data("Lahman_2024u/People.csv")
YData_baseball.download_data("Lahman_2024u/Batting.csv")
YData_baseball.download_data("Lahman_2024u/Teams.csv")
#YData_baseball.download_image("george_brett.png")

The file `People.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `Batting.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `Teams.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.

# Part 0: Quote and reaction to Astroball chapter 1 (5 points)

Please find an interesting quote from chapter 2 of Astroball (preface or prologue) and then write a ~one paragraph reaction to the quote below.

*Quote:*  ...

Reaction: ...

# Part 1. More advanced pandas and writing functions

In this lab, you will continue where you left off in lab 1 by analyzing the Lahman Batting data using pandas. In particular, you will use pandas and write functions to get (approximately) recreate the baseball card you were given in the first class. 

To start, you will recreate a baseball card I randomly selected which is the Topps 1991 baseball card for George Brett, which is shown below. You will then convert your code into a function that can be used to get a baseball card for any player in the Lahman database. 

These exercises might be challenging so try your best, and if you get stuck please ask questions on Ed Discussion. Also, if you complete these exercises, please help your your peers by answering questions on Ed. Good luck!

![](george_brett.png)

###  1.1 Getting data on an individual player (5 points)

Each baseball player in the Lahman database has a unique playerID. We can use this playerID to get data on a specific player. 

The code below loads the Lahman People data into a pandas DataFrame called `players`. This DataFrame contains information on all players in the Lahman database, including their playerID, first name, last name, and other information. 

To start, let's write code that creates a variable called `player_info` which only has one row for the `players` DataFrame which corresponds one specific player. In particular, we have created variables `first_name` and `last_name` that contain the first and last name of the player we want to get data for (in this case, George Brett), so write code that use these `first_name` and `last_name` variables to reduce the `players` DataFrame to a single row that matches this one player and save this single row to one row DataFrame called `player_info`. 

For this, and all questions below, be sure to "show your work" by printing out your results in the Python cells. If the results are simple values, you can just display them, and if the results are a DataFrame, use the `.head()` method to show the first few rows of the DataFrame. 

Hint: There are a few ways to do this. One way would be to do multiple rows of Boolean Indexing to filter the DataFrame on the `first_name`, and then on the `last_name`, but you can also do this in a single line of code using the `&` operator to combine two Boolean conditions. Either solution is fine (or even another solution if you can think of another way to do this).

In [2]:
import pandas as pd

players = pd.read_csv("People.csv") 

players.head()

,ID,playerID,birthYear,birthMonth,birthDay,birthCity,birthCountry,birthState,deathYear,deathMonth,...,nameLast,nameGiven,weight,height,bats,throws,debut,bbrefID,finalGame,retroID
0,1,aardsda01,1981.0,12.0,27.0,Denver,USA,CO,NaN,NaN,...,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,aardsda01,2015-08-23,aardd001
1,2,aaronha01,1934.0,2.0,5.0,Mobile,USA,AL,2021.0,1.0,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,aaronha01,1976-10-03,aaroh101
2,3,aaronto01,1939.0,8.0,5.0,Mobile,USA,AL,1984.0,8.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,aaronto01,1971-09-26,aarot101
3,4,aasedo01,1954.0,9.0,8.0,Orange,USA,CA,NaN,NaN,...,Aase,Donald William,190.0,75.0,R,R,1977-07-26,aasedo01,1990-10-03,aased001
4,5,abadan01,1972.0,8.0,25.0,Palm Beach,USA,FL,NaN,NaN,...,Abad,Fausto Andres,184.0,73.0,L,L,2001-09-10,abadan01,2006-04-13,abada001

In [3]:
# Get the only one row from players DataFrame that matches the name stored in the first_name and last_name variables

first_name = "George"
last_name = "Brett"

### 1.2 Return a string with only his playerID (5 points)

Next please write code that extracts the playerID **as a string** from the `player_info` DataFrame we just created. The playerID is a string that uniquely identifies the player in the Lahman database. 

Again, for this and all questions below, be sure to "show your work" by printing out your results in the Python cells. 

Hint: The `.iloc` method could be useful to extract the string that has the playerID from a Series that has this information.

### 1.3 Write a function that returns a playerID (5 points)

Now, let's turn what we just did into a function. The function should be called `get_playerID` and should take the arguments `first_name` and `last_name` as input, and return the playerID as a string. This will allow us to easily get the playerID for any player in the Lahman database. 

Once you have written the function, use the code below to test your function by getting the playerID for George Brett and Aaron Judge.

In [4]:
# 1.3 Write a function that returns a playerID

def get_playerID(first_name, last_name):
    ...





# Test your code
print(get_playerID("Aaron", "Judge"))
playerID = get_playerID("George", "Brett")
playerID

None

## 1.4 Get batting data from player with a given playerID (5 points)

Now that we have a function to get a playerID, let's use this to get the batting data for the player with the playerID we just got. The Lahman Batting data is stored in a DataFrame called `batting`, which we can load using the code below. Using the `playerID` variable we just created (which should have the playerID for George Brett), please write code that gets the batting data for the player with this playerID and stores it in a DataFrame called `player_data`. Also, as always print out the first few rows of this DataFrame to show that it has the data we expect using the `.head()` method.

In [5]:
# Get batting data from player with a given playerID

batting = pd.read_csv("Batting.csv")  
batting.head()


# Answer

,playerID,yearID,stint,teamID,lgID,G,G_batting,AB,R,H,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,G_old
0,aardsda01,2004,1,SFN,NL,11,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,aardsda01,2006,1,CHN,NL,45,NaN,2,0,0,...,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
2,aardsda01,2007,1,CHA,AL,25,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,aardsda01,2008,1,BOS,AL,47,NaN,1,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
4,aardsda01,2009,1,SEA,AL,73,NaN,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

## 1.5 Get data only up to a particular year (5 points)

Baseball cards only show data up to a certain year, so let's filter the data to only include data up to a particular year. In this case, we will use the year 1990, since the George Brett cards was a 1991 Topps card that only had data through the 1990 season. 

The variable `end_year` is set to 1990. Please write code that filters the `player_data` DataFrame to only include rows where the `yearID` is less than or equal to the `end_year` and stores this in a new DataFrame called `player_data2`. 

Note: your code should use the `end_year` variable and should not hard code the value 1990.

In [6]:

end_year = 1990

## 1.6 Write helper functions to calculate batting average and slugging percentage

Now let's write some helper functions to calculate the batting average (AVG) and slugging percentage (SLG) for each season in a given Lahman batting DataFrame (such as the `player_data2` created above). Recall that the definition of batting average is: $$\text{AVG} = \frac{\text{H}}{\text{AB}}$$ where H is the number of hits and AB is the number of at-bats. The definition of slugging percentage is: $$\text{SLG} = \frac{\text{1B} + 2 \cdot \text{2B} + 3 \cdot \text{3B} + 4 \cdot \text{HR}}{\text{AB}}$$ where 1B, 2B, 3B, and HR are the number of doubles, triples, and home runs, respectively. You have already code to calculate the slugging percentage in lab 1, so you can use that as a starting point. 

The function you write should be called `calc_AVG_and_SLG(lahman_batting)` and and as mentioned should take in a Lahman batting DataFrame (such as `player_data2`). The function should return a tuple with the batting average and slugging percentage for each season in the DataFrame. 

Once you have written the function use the code below to call the function on the `player_data2` DataFrame, and to store the results in the variables `SLG` and `AVG`. Then print out the values of `SLG` to show that they are correct.

In [7]:
# Write helper functions to calculate batting average and slugging percentage

def calc_AVG_and_SLG(lahman_batting):
    ...

## 1.7 Add AVG and SLG to the data (5 points)

Now write code to create a DataFrame called `player_data3` that has the same data as `player_data2` but also has two new columns called `AVG` and `SLG` that contain the batting average and slugging percentage for each season in the DataFrame. Use the `AVG` and `SLG` variables you just created to populate these new columns.

In [8]:

# Uncomment the code below to create the initial player_data3 DataFrame. Then add AVG and SLG columns to this DataFrame

#player_data3 = player_data2.copy()

## 1.8 Adding team names to the data (5 points)

The information identifying which baseball team a player played for in each season is contained in the column `teamID` in the Lahman Batting data. However, this column only contains a short code for the team name (e.g., "KCA" for the Kansas City Royals). To get the full team name, we need to join the Lahman Teams data with the Lahman Batting data. 

The code below loads the `Teams.csv` file into a DataFrame called `teams`. This DataFrame contains information on all teams in the Lahman database, including the teamID, yearID, and team name.  Please do the following to add the full team names to the `player_data3` DataFrame:

1. Reduce the `teams` DataFrame to only the columns `teamID`, `yearID`, and `name` (the full team name).
   
2. Merge the `player_data3` DataFrame with the `teams` DataFrame on the columns `teamID` and `yearID`. This will add the full team name to the `player_data3` DataFrame. Store the results of this new merged DataFrame in a variable called `player_data4`.

3. As always, print out the first few rows of the `player_data4` DataFrame to show that it has the data we expect.

In [9]:
# Load the teams data and merge with player data

teams = pd.read_csv("Teams.csv")

teams.tail()

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
3579,2024,NL,SLN,STL,C,2,162,81.0,83,79,...,155.0,0.987,St. Louis Cardinals,Busch Stadium III,2878115.0,100.0,100.0,STL,SLN,SLN
3580,2024,AL,TBA,TBD,E,4,162,81.0,80,82,...,108.0,0.984,Tampa Bay Rays,Tropicana Field,1337739.0,99.0,99.0,TBR,TBA,TBA
3581,2024,AL,TEX,TEX,W,3,162,81.0,78,84,...,106.0,0.987,Texas Rangers,Globe Life Field,2651553.0,96.0,96.0,TEX,TEX,TEX
3582,2024,AL,TOR,TOR,E,5,162,81.0,74,88,...,125.0,0.984,Toronto Blue Jays,Rogers Centre,2681236.0,103.0,103.0,TOR,TOR,TOR
3583,2024,NL,WAS,WSN,E,4,162,81.0,71,91,...,155.0,0.981,Washington Nationals,Nationals Park,1967302.0,96.0,98.0,WSN,MON,WAS

In [10]:
# Create the player_data4 DataFrame here

## 1.9 Rename the "name" column to Club (5 points)

The column that we just added to the `player_data4` DataFrame is called `name`, but we want to rename this column to `Club` to match the baseball card. Please write code that renames the `name` column to `Club` in the `player_data4` DataFrame and stores the results in a new DataFrame called `player_data5`. 

Note: On the actualy Topps baseball card, the Club is listed as the Royals rather than the Kansas City Royals. In order to keep these analyses a little simpler, please just keep this longer name for the purposes of this exercise.

## 1.10 Get only the columns on the baseball card (5 points)

Let's now reduce the `player_data5` DataFrame to only the columns that are shown on the baseball card. The columns we want to keep are: `yearID`, `Club`, `G`, `AB`, `R`, `H`, `2B`, `3B`, `HR`, `RBI`, `SB`, `SLG`, `BB`, `SO`, and `AVG` (in that order!). Please write code that reduces the DataFrame to only these columns and stores the results in a new DataFrame called `player_data6`.

## 1.11 Calculate totals for each statistic (5 points)

The last line of the baseball card shows a player's (current) career totals for each statistic. Let's calculate these totals for the data in the `player_data6` DataFrame. Please write code that calculates the totals for all statistics in the `player_data6` DataFrame and stores the results in a new Series called `player_totals`. 

Hint: This can be done in a single line of code.

## 1.12 Add summary stats to totals (5 points)

Now let's add four  new columns to the `player_totals` Series. The first two columns should be called `AVG` and `SLG` and should contain the batting average and slugging percentage for the player's career totals. You can use the `calc_AVG_and_SLG` function you wrote earlier to calculate these values. 

Once you have calculated added AVG and SLG, also add a column called `yearID` and should be set to the string `"Total"`, and a column called `Club` and should be set to the empty string `""`.

In [11]:
# Add additional summary stats to player_totals

## 1.13 Combine the totals with the original data

Next let's add the `player_totals` to the `player_data6` DataFrame. To do this, please use the following steps.

1. Convert the `player_totals` Series to a DataFrame using the `.to_frame()` method. Save this DataFrame to a variable called `totals_df`.

2. Transpose the `totals_df` DataFrame using the `.T` property to make it a single row DataFrame. Save this transposed DataFrame to a variable called `totals_df_transpose` (note, since the transpose operation involves changing a property of the DataFrame rather than calling a method, `.T` we do not use paratheses after `.T`).

3. Create a list called `data_totals_list` that contains the `player_data6` DataFrame and the `totals_df_transpose` DataFrame. 

4. Call the `pd.concat()` function on the `data_totals_list` to combine the player statistics and total into a single DataFrmae. Be sure to set the `ignore_index` argument of the `pd.concat()` function to `True` so that the index is reset. Save the results to a new DataFrame called `player_data7`.

5. For this, and the rest of the exercises below, use the `.tail()` method (rather than the `.head()` method) to show your work for this problem.

## 1.14 Set index to year (5 points)

To make the results look a little more clean, let's set the index of the `player_data7` DataFrame to the year that each row of statistics comes from. To do this, please use the following steps:

1. Use the `.rename()` method to rename the `yearID` column to `YR` in the `player_data7` DataFrame. Save the results to a new DataFrame called `player_data8`.

2. Use the `.set_index()` method to set the index of the `player_data8` DataFrame to the `YR` column. Save the results to the same `player_data8` DataFrame. 

Note: On the baseball card, the year is shown as just the last two digits of the year, but we will keep the full year.

## 1.15 Round values to integers (5 points)

We're almost done. Let's round some of the values in the `player_data8` DataFrame to integers to make the results look cleaner (and also better match the baseball card). In particular, we will round the `RBI`, `SB`, and `SO` columns to integers using the `astype("int")` method. Please write code that does this and stores the results back in the `player_data8` DataFrame.

## 1.16 Write a function that does everything (10 points)

Finally, let's write one function produces the full baseball card (i.e., that does everything we just did above). This function should called `get_baseball_card(first_name, last_name, end_year)` and should take in a player's first name, last name, and the last year of data to include on the baseball card, and return a DataFrame with the player's statistics for each year up to and including the `end_year`, as well as the player's career totals. The DataFrame should have the same format as the `player_data8` DataFrame we created above. 

Once you have written this function call it on:

1. George Brett with an end year of 1990 to verify the function works as expected.

2. The player on the baseball card you were given in class to fully replicate that card.

3. One additional player whose statistics you are interested in seeing.

Please print out the full data (i.e., baseball card) for each player you test the function on.

In [12]:

def get_baseball_card(first_name, last_name, end_year):
    ...

















# Replicate the George Brett results
display(get_baseball_card("George", "Brett", 1990))



# Add your baseball card here and another player you find interesting

None

## 2. If you feel inspired, explore the Lahman or retrodata further (0 points)

If you found the lab was easy, feel free to challenge yourself doing some additional analyses on the Lahman or retrosheet data and show off your work below. This part is not worth any points, but it is a good way to practice your pandas skills and learn more about baseball.

# 3.  Submitting your work

Once you're finished filling in and running all cells, you should submit your assignment as a pdf on Gradescope. You can access Gradescope through Canvas on the left-side of the class home page. The problems in each lab assignment are numbered. When submitting on Gradescope, please **make sure to select the correct pages of your pdf that correspond to each problem**. Failure to mark pages correctly **will result in points being deducted** from your score.

To convert this Jupyter notebook document to a pdf please run the code in the cell below. This should produce a document called `lab_02.pdf` which should appear in the files tab on the left (you might need to refresh the files tab to see this file). You can then right click on this file (command click on a mac), to download this pdf document which you can upload to Gradescope. 

Please be sure to check that all the code and output are visible before submitting your pdf to Gradescope as **points will be deducted for missing code and output that is not visible** since we will not be able to grade this.

In [13]:
%%capture

!quarto render lab_02.ipynb --cache-refresh --to pdf

#### Alternative submission instructions

If converting your Jupyter notebook to a pdf using the command in the cell above does not work, an alternative way to convert your Jupyter notebook is:

1.  Go to "File" at the top-left of your Jupyter Notebook
2.  Under "Download as" (or "Save and Export Notebook As...") and select "HTML (.html)"
3.  After the .html has downloaded, open it and then select "File" and "Print" (note you will not actually be printing)
4.  From the print window, select the option to save as a .pdf